name: Deploy con Terraform y LocalStack

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Inicializar Terraform
      run: terraform init

    - name: Planificar
      run: terraform plan

    - name: Aplicar configuración
      run: terraform apply -auto-approve
