name: Deploy con Terraform y LocalStack

on: [push]

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    options: >-
      --health-cmd "curl -f http://localhost:4566/health || exit 1"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Inicializar Terraform
      run: terraform init

    - name: Planificar
      run: terraform plan

    - name: Aplicar configuración
      run: terraform apply -auto-approve
