name: CI/CD Terraform con LocalStack

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Validar configuración
        run: terraform validate

      - name: Iniciar LocalStack
        uses: LocalStack/setup-localstack@v0.1.3
        with:
          image-tag: "latest"

      - name: Inicializar Terraform
        run: terraform init

      - name: Planificar infraestructura
        run: terraform plan

      - name: Aplicar infraestructura
        run: terraform apply -auto-approve
